### ISSUE TITLE
I can try and do some music

### ISSUE THREAD

**Issue by BushTrain460615** [khuonghoanghuy/AdventureHaxe#2]
I have been making music for about 5 months when the song is up on Spotify I can show an example of my song

**Comment by MemeHoovy** [comment]
well okay then

**Comment by khuonghoanghuy** [comment]
Hope is good

**Comment by BushTrain460615** [comment]
I can make a main menu song real quick if you want

**Comment by BushTrain460615** [comment]
<img width="1245" alt="Screenshot 2022-11-06 at 10 11 23 AM" src="https://user-images.githubusercontent.com/72326501/200181711-42c25903-bcd3-4cdd-b671-3b48021affe2.png">
I made a piano that is calming of the main menu

**Comment by khuonghoanghuy** [comment]
@BushTrain460615 where the music game release on?

**Comment by BushTrain460615** [comment]
> @BushTrain460615 where the music game release on?

I can put it in the music folder if you want me too

**Comment by MemeHoovy** [comment]
me getting ready to not do anything in this repo for the next few weeks: (I'm too lazy)

![Extra_Springtrap_1 (1)](https://user-images.githubusercontent.com/97995998/201000897-1a973916-8cc9-4cc3-a662-89939f98d534.png)

**Comment by khuonghoanghuy** [comment]
Oh

**Comment by MemeHoovy** [comment]
> Oh

I was joking

**Comment by BushTrain460615** [comment]
can I have your discord if you have one

**Comment by MemeHoovy** [comment]
> can I have your discord if you have one

huy1234th#0146

**Comment by BushTrain460615** [comment]
I will DM the music to you and let me know if it is good

**Comment by MemeHoovy** [comment]
to who? huy or me?

**Comment by BushTrain460615** [comment]
huy

**Comment by khuonghoanghuy** [comment]
Oh
